### ISSUE TITLE
Custom value in item

### ISSUE THREAD

**Issue by deathart** [rowanmanning/feed-parser#156]
Hello,

First of all, thank you for your package, which works like a charm!

I have a question, in the items, is it possible to recover custom elements?

An example on this site: https://www.xboxygen.com/spip.php?page=backend

The key/value of dc:subject corresponds to category but it's impossible to retrieve the value at the moment.

Did I misread the readme or is it currently impossible to retrieve the value?

**Comment by rowanmanning** [comment]
Hi @deathart, thanks! Glad you're finding it useful 🙂 adding the ability to pull custom elements isn't on the roadmap at the moment (and it'd be quite a big overhaul so I'm unlikely to do it) however I _thought_ I was already parsing `dc:subject`. Turns out that I'm not!

I'd be happy to either do the work to pull `dc:subject` into feed and item `categories` if that works for you?

**Comment by rowanmanning** [comment]
I decided it was worth adding anyway. [Give `v1.1.0` a go](https://github.com/rowanmanning/feed-parser/releases/tag/v1.1.0) and see if this works for you? I tested it with your feed and each entry now has a single category.

**Comment by deathart** [comment]
Hello, thanks for this update, You solved the problem.
